version: '2'

services:
  # this is our kafka cluster.
  kafka-cluster:
    platform: linux/amd64
    image: zachmartinkr/fast-data-dev
    build:
      context: . 
      dockerfile: Dockerfile 
    environment:
      ADV_HOST: 127.0.0.1         
      RUNTESTS: 0                 
      KAFKA_MESSAGE_MAX_BYTES: 2097152
      AWS_ACCESS_KEY_ID: <access_key_id>
      AWS_SECRET_ACCESS_KEY: <secret_access_key>
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker